'use strict';
const $ = s => document.querySelector(s);
let eventOffset = 0, timelineDragging = false;
let csrf = '', settings = null, currentTab = 'overview', eventParts = [], partIndex = 0, timer;
const titles = {overview:'Под присмотром', events:'Архив событий', cameras:'Камеры', settings:'Настройки'};
const el = (tag, text, cls) => { const n = document.createElement(tag); if(text !== undefined) n.textContent = text; if(cls) n.className = cls; return n; };
function toast(message) { $('#toast').textContent = message; $('#toast').hidden = false; clearTimeout(timer); timer = setTimeout(() => $('#toast').hidden = true, 7000); }
async function api(path, method='GET', body) { const r = await fetch('/api/v1'+path, {method, headers: {'Content-Type':'application/json', 'X-CSRF-Token':csrf}, body:body===undefined?undefined:JSON.stringify(body)}); if(r.status===204) return null; const data = await r.json(); if(!r.ok) {if(r.status===401 && path!='/login') showLogin(false); throw Error(data.error||'Не удалось выполнить запрос');} return data; }
function run(fn) { return async ev => { if(ev) ev.preventDefault(); const b = ev?.submitter || (ev?.currentTarget?.tagName==='BUTTON' ? ev.currentTarget : null); if(b) b.disabled=true; try {await fn(ev);} catch(e) {toast(e.message);} finally {if(b) b.disabled=false;} }; }
function field(form, name) { return form.elements.namedItem(name); }
function time(ms) { return new Intl.DateTimeFormat('ru-RU', {timeZone:settings?.timezone||'Europe/Moscow', day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(ms)); }
function bytes(n) { if(!n) return '0 Б'; const units=['Б','КБ','МБ','ГБ','ТБ']; const i=Math.min(4,Math.floor(Math.log(n)/Math.log(1024))); return (n/1024**i).toFixed(i>1?1:0)+' '+units[i]; }
const nameOf = id => settings?.cameras.find(c=>c.id===id)?.name || 'Удалённая камера';
function empty(target, text) { target.replaceChildren(el('div',text,'empty')); }
function showLogin(setup) { $('#shell').hidden=true;$('#login').hidden=false;$('#setup-label').hidden=!setup;$('#login-description').textContent=setup?'Создайте пароль администратора и введите код первого запуска.':'Войдите в Dozor, чтобы открыть записи.'; }
async function init() { const a=await api('/auth');if(!a.authenticated){showLogin(a.setup_required);return;}csrf=a.csrf;await enter(); }
async function enter() {$('#login').hidden=true;$('#shell').hidden=false;settings=await api('/settings');fillSettings();renderCameras();await status();await loadEvents();}
$('#login-form').addEventListener('submit',run(async()=>{const f=$('#login-form');const a=await api('/login','POST',{password:field(f,'password').value,token:field(f,'token').value});csrf=a.csrf;f.reset();await enter();}));
$('#logout').onclick=run(async()=>{await api('/logout','POST',{});csrf='';$('#video').pause();$('#video').removeAttribute('src');showLogin(false);});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=run(async()=>{currentTab=b.dataset.tab;document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==currentTab);document.querySelectorAll('nav button').forEach(n=>n.classList.toggle('active',n.dataset.tab===currentTab));$('#page-title').textContent=titles[currentTab];if(currentTab==='events')await loadEvents();}));
async function status() {const s=await api('/status');$('#today').textContent=new Intl.DateTimeFormat('ru-RU',{dateStyle:'long',timeZone:settings.timezone}).format(new Date());$('#version').textContent='Dozor '+s.version;$('#system-badge').textContent=s.disk_ready?'Система работает':'Требуется настройка диска';$('#storage-alert').hidden=s.disk_ready;$('#storage-alert').textContent=s.storage_error||'Подключите и выберите диск в настройках.';$('#stat-cameras').textContent=s.cameras.filter(c=>c.online).length+' / '+settings.cameras.filter(c=>c.enabled).length;$('#stat-disk').textContent=s.disk_total?Math.round(100*s.disk_used/s.disk_total)+'%':'—';$('#stat-disk-detail').textContent=s.disk_total?bytes(s.disk_used)+' из '+bytes(s.disk_total):'ожидаем диск';$('#stat-queue').textContent=s.queue;$('#stat-queue-detail').textContent=settings.s3.enabled?'части и описания событий':'выгрузка выключена';$('#s3-alert').hidden=!settings.s3.enabled||!s.upload_error;$('#s3-alert').textContent=s.upload_error||'';const grid=$('#camera-status');grid.replaceChildren();if(!settings.cameras.length)empty(grid,'Добавьте первую камеру — с поиска в сети или по RTSP-адресу.');for(const c of s.cameras){const card=el('article',undefined,'camera-card');card.append(el('h3',c.name),el('p',c.online?'Поток поступает':'Нет свежих фрагментов','muted'),el('span',!c.enabled?'Отключена':!c.detector_healthy?'Резервная непрерывная запись':c.motion?'Есть движение':'Наблюдение','badge'));grid.append(card);}const notices=$('#notices');notices.replaceChildren();if(!s.notices.length)notices.append(el('p','Сообщений пока нет.','muted'));for(const n of s.notices){const row=el('div',undefined,'notice');row.append(el('time',time(n.at)),el('span',n.message));notices.append(row);}if(s.update_status)$('#update-status').textContent=s.update_status;}
function renderCameras(){const grid=$('#camera-list');grid.replaceChildren();const filter=$('#filter-camera'),selected=filter.value;filter.replaceChildren(new Option('Все камеры',''));for(const c of settings.cameras){filter.add(new Option(c.name,c.id));const card=el('article',undefined,'camera-card');card.append(el('h3',c.name),el('p',c.url,'muted'));const actions=el('div',undefined,'actions');const edit=el('button','Настроить','secondary');edit.onclick=()=>editCamera(c);const del=el('button','Удалить','text-button');del.onclick=run(async()=>{if(!confirm('Удалить камеру из конфигурации? Существующие события останутся.'))return;await api('/cameras/'+c.id,'DELETE');settings=await api('/settings');renderCameras();});actions.append(edit,del);card.append(actions);grid.append(card);}filter.value=selected;if(!settings.cameras.length)empty(grid,'Камер пока нет. Добавьте первую справа вверху.');}
function editCamera(c={id:'',name:'',url:'',sub_url:'',onvif:'',username:'admin',motion:'auto',sensitivity:.7,masks:[],enabled:true}){const f=$('#camera-form');f.hidden=false;$('#camera-form-title').textContent=c.id?'Настройка камеры':'Новая камера';for(const k of ['id','name','url','sub_url','onvif','username','motion','sensitivity'])field(f,k).value=c[k]??'';field(f,'password').value='';field(f,'masks').value=JSON.stringify(c.masks||[]);field(f,'enabled').checked=c.enabled;$('#probe-result').textContent='';$('#profiles').replaceChildren();f.scrollIntoView({behavior:'smooth',block:'start'});}
function cameraData(){const f=$('#camera-form');const c={};for(const k of ['id','name','url','sub_url','onvif','username','password','motion'])c[k]=k==='password'?field(f,k).value:field(f,k).value.trim();c.sensitivity=Number(field(f,'sensitivity').value);c.enabled=field(f,'enabled').checked;try{c.masks=JSON.parse(field(f,'masks').value);}catch{throw Error('Проверьте JSON исключаемых областей');}return c;}
$('#add-camera').onclick=()=>editCamera();$('#close-camera').onclick=()=>$('#camera-form').hidden=true;
$('#camera-form').onsubmit=run(async()=>{const c=cameraData();await api('/cameras/'+(c.id||'new'),'PUT',c);settings=await api('/settings');renderCameras();$('#camera-form').hidden=true;toast(c.enabled?'Камера сохранена. Подключаем потоки.':'Камера сохранена и выключена.');});
$('#probe-camera').onclick=run(async()=>{const p=await api('/cameras/probe','POST',cameraData());$('#probe-result').textContent=`${p.width} × ${p.height} · ${p.video} · звук: ${p.audio||'нет'} · ${p.browser_compatible?'подходит для браузера':'просмотр зависит от поддержки кодеков браузером'}`;});
$('#get-profiles').onclick=run(async()=>{const ps=await api('/profiles','POST',cameraData());const target=$('#profiles');target.replaceChildren();if(!ps.length)empty(target,'Профили не найдены. Укажите RTSP-адрес вручную.');for(const p of ps){const row=el('div',undefined,'panel');row.append(el('p',p.name+' · '+p.url));const main=el('button','Основной поток','secondary');main.type='button';main.onclick=()=>field($('#camera-form'),'url').value=p.url;const sub=el('button','Для детектора','secondary');sub.type='button';sub.onclick=()=>field($('#camera-form'),'sub_url').value=p.url;const actions=el('div',undefined,'actions');actions.append(main,sub);row.append(actions);target.append(row);}});
$('#discover').onclick=run(async()=>{const v=await api('/discovery','POST',{});const target=$('#discovery-results');target.hidden=false;target.replaceChildren(el('h3','Найдено в сети'));if(!v.length)target.append(el('p','Камеры не ответили. ONVIF может быть выключен; используйте ручное добавление.','muted'));for(const c of v){const b=el('button',c.endpoint,'secondary');b.onclick=()=>{editCamera();field($('#camera-form'),'onvif').value=c.endpoint;field($('#camera-form'),'name').value='Камера '+new URL(c.endpoint).hostname;};target.append(b);}});
async function loadEvents(append){append=append===true;if(!append)eventOffset=0;if(!settings)return;const q=new URLSearchParams({offset:String(eventOffset)});if($('#filter-camera').value)q.set('camera',$('#filter-camera').value);if($('#filter-date').value)q.set('date',$('#filter-date').value);let v;try{v=await api('/events?'+q);}catch(e){empty($('#event-list'),e.message);return;}const target=$('#event-list');if(!append)target.replaceChildren();else target.querySelector('[data-more]')?.remove();eventOffset+=v.length;if(!v.length&&!append)empty(target,'За выбранный период событий пока нет.');for(const ev of v){const b=el('button',undefined,'event-item');b.append(el('strong',nameOf(ev.camera_id)),el('span',time(ev.start)),el('small',ev.status!=='closed'?'Записывается…':ev.lost?'Есть потери до загрузки':ev.uploaded?'Копия в S3 подтверждена':'Ожидает выгрузки'));b.onclick=run(async()=>{target.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');await openEvent(ev.id);});target.append(b);}if(v.length===200){const more=el('button','Загрузить ещё','secondary');more.dataset.more='true';more.onclick=run(()=>loadEvents(true));target.append(more);}}
async function openEvent(id){const {event:e,parts}=await api('/events/'+id);$('#event-title').textContent=nameOf(e.camera_id);$('#event-info').textContent=time(e.start)+' — '+time(e.end)+(e.short_prebuffer?' · неполная предыстория':'')+(e.incomplete?' · есть пропуски':'')+(e.lost?' · часть записей удалена до выгрузки':'');eventParts=parts.filter(p=>!p.deleted);$('#timeline-label').hidden=!eventParts.length;if(eventParts.length){$('#timeline').min=eventParts[0].start;$('#timeline').max=eventParts[eventParts.length-1].end;}$('#parts').replaceChildren();for(const [i,p]of eventParts.entries()){const b=el('button',time(p.start),'secondary');b.onclick=()=>playPart(i);$('#parts').append(b);}if(eventParts.length)playPart(0);else{$('#video').pause();$('#video').removeAttribute('src');$('#video').load();$('#download').hidden=true;$('#parts').append(el('p','На диске нет готовых частей. Событие ещё собирается или локальные копии уже удалены.','muted'));}}
function playPart(i, offset=0){partIndex=i;const p=eventParts[i];$('#timeline').value=p.start;$('#timeline-time').textContent=time(p.start);$('#video').onloadedmetadata=()=>{$('#video').currentTime=offset;};$('#video').src='/api/v1/parts/'+p.id+'/video';$('#download').href=$('#video').src+'?download=1';$('#download').hidden=false;$('#parts').querySelectorAll('button').forEach((b,j)=>b.classList.toggle('secondary',i!==j));}
$('#video').onerror=()=>{if($('#video').getAttribute('src'))toast('Видео недоступно или кодек не поддерживается браузером. Проверьте наличие записи и попробуйте скачать часть.');};
$('#video').onended=()=>{if(partIndex+1<eventParts.length){playPart(partIndex+1);$('#video').play().catch(()=>{});}};
$('#refresh-events').onclick=run(loadEvents);$('#filter-camera').onchange=run(loadEvents);$('#filter-date').onchange=run(loadEvents);
function fillSettings(){const f=$('#settings-form'),s=settings.s3;for(const k of ['endpoint','region','bucket','prefix'])field(f,k).value=s[k]||'';field(f,'s3_enabled').checked=s.enabled;field(f,'path_style').checked=s.path_style;field(f,'rate').value=s.bytes_per_second/1024;field(f,'timezone').value=settings.timezone;field(f,'auto_update').checked=settings.auto_update;field(f,'release_url').value=settings.release_url||'';field(f,'access_key').value='';field(f,'secret_key').value='';}
$('#settings-form').onsubmit=run(async()=>{const f=$('#settings-form'),s={};for(const k of ['endpoint','region','bucket','prefix','access_key','secret_key'])s[k]=field(f,k).value.trim();s.enabled=field(f,'s3_enabled').checked;s.path_style=field(f,'path_style').checked;s.bytes_per_second=Math.round(Number(field(f,'rate').value)*1024);await api('/settings','PUT',{timezone:field(f,'timezone').value,s3:s,auto_update:field(f,'auto_update').checked,release_url:field(f,'release_url').value});settings=await api('/settings');fillSettings();toast('Настройки сохранены. Службы переподключаются.');});
$('#load-disks').onclick=run(async()=>{const v=await api('/disks'),target=$('#disk-list');target.replaceChildren();if(v.development){target.append(el('p','Режим разработки: используется явно указанный каталог. Выбор физического диска доступен на Raspberry Pi.','muted'));return;}function render(d){const row=el('div',undefined,'notice');row.append(el('span',`${d.model||d.name} · ${bytes(Number(d.size))} · ${d.fstype||'без файловой системы'} · ${d.uuid||'нет UUID'} · ${d.fsavail==null?'свободное место — после монтирования':'свободно '+bytes(Number(d.fsavail))}`));if(d.uuid&&d.fstype==='ext4'){const b=el('button',d.uuid===v.selected_uuid?'Выбран':'Использовать','secondary');b.disabled=d.uuid===v.selected_uuid;b.onclick=run(async()=>{if(!confirm('Использовать этот ext4-раздел для архива Dozor? Файлы не форматируются.'))return;await api('/disks/select','POST',{uuid:d.uuid});toast('Диск выбран');});row.append(b);}target.append(row);for(const child of d.children||[])render(child);}for(const d of v.disks)render(d);});
setInterval(()=>{if(!$('#shell').hidden)status().catch(e=>toast(e.message));},10000);
init().catch(e=>toast(e.message));

// Map the concatenated media time to wall clock time, preserving known gaps.
function clockTime(p, seconds) {
  let value=p.start+seconds*1000;
  for(const gap of p.gaps||[]){if(gap.start>=p.start&&value>=gap.start)value+=gap.end-gap.start;}
  return Math.min(value,p.end);
}
$('#timeline').onpointerdown=()=>{timelineDragging=true;};
$('#timeline').onpointercancel=()=>{timelineDragging=false;};
$('#timeline').oninput=()=>{timelineDragging=true;$('#timeline-time').textContent=time(Number($('#timeline').value));};
$('#timeline').onchange=()=>{
  timelineDragging=false;
  const target=Number($('#timeline').value);
  const i=eventParts.findIndex(p=>target>=p.start&&target<=p.end);
  if(i<0){toast('В выбранное время нет локальной записи.');return;}
  const p=eventParts[i];let offset=target-p.start;
  for(const gap of p.gaps||[]){
    if(target>=gap.start&&target<gap.end){toast('В выбранное время был разрыв потока.');return;}
    if(gap.start>=p.start&&gap.end<=target)offset-=gap.end-gap.start;
  }
  if(i===partIndex){$('#video').currentTime=offset/1000;}else{playPart(i,offset/1000);}
};
$('#video').ontimeupdate=()=>{
  const p=eventParts[partIndex];if(!p||timelineDragging)return;
  const value=clockTime(p,$('#video').currentTime);
  $('#timeline').value=value;$('#timeline-time').textContent=time(value);
};
