// Entry of the Dozor menu bundle (see ../build.mjs): the shared Sidebar of @jourloy/00, mounted by app.js.
//
// app.js keeps the routing; the menu only reads location.hash to mark the current item (aria-current="page")
// and follows hashchange. Everything the bundle needs from the page arrives through DozorMenu.mount(el, options).
import {useMemo, useSyncExternalStore, type ComponentType, type AnchorHTMLAttributes} from "react";
import {createRoot} from "react-dom/client";
import {SidebarShell} from "@jourloy/00/components/SidebarShell";
import {
  darkSidebarShellClassNames,
  darkSidebarUtilityClassName,
} from "@jourloy/00/components/SidebarDarkTheme";
// Tailwind utilities that the Sidebar markup relies on (generated by build.mjs), then the host adjustments.
import "a00-tailwind";
import "./host.css";

/** One destination. `hash` is the href ("#overview"), `icon` is the id of the page's SVG sprite without "i-". */
type MenuItem = {hash: string; label: string; icon: string};

// Every text the Sidebar renders. The page passes all of them: a label missing here would fall back to the package's
// own default, and a change of that default upstream would silently change Dozor's text. build.mjs fails when the
// package has a label that is not listed here.
const SIDEBAR_LABEL_KEYS = ["collapse", "pin", "navigation", "brandTitle", "brandSigil", "brandAriaLabel"] as const;
type SidebarLabels = Record<(typeof SIDEBAR_LABEL_KEYS)[number], string>;

function assertLabels(labels: Partial<SidebarLabels> | undefined) {
  const missing = SIDEBAR_LABEL_KEYS.filter(key => !labels || typeof labels[key] !== "string" || labels[key] === "");
  if (missing.length > 0) throw new Error(`DozorMenu: labels missing: ${missing.join(", ")}`);
}

type MenuOptions = {
  /** The first item is the home item: the brand link goes there too, and it is the fallback of an unknown hash. */
  items: MenuItem[];
  /** navigation is the aria-label of the landmark; brandTitle and brandSigil draw the brand next to the version. */
  labels: SidebarLabels;
  /** Text under the brand name in the expanded rail. */
  version?: string;
  logoutLabel: string;
  onLogout: (event: unknown) => unknown;
};

type SidebarIcon = ComponentType<{className?: string; "aria-hidden"?: boolean}>;
type LinkProps = Omit<AnchorHTMLAttributes<HTMLAnchorElement>, "href"> & {href: string};

/** A plain anchor: the routing is the hash, there is no router to hand the navigation over to. */
function PlainLink(props: LinkProps) {
  return <a {...props} />;
}

// The page owns its icons as an SVG sprite (<symbol id="i-…">, drawn by .ui-icon). One component per id, created once:
// a new component type on every render would remount the icons.
const icons = new Map<string, SidebarIcon>();
function spriteIcon(id: string): SidebarIcon {
  let Icon = icons.get(id);
  if (!Icon) {
    Icon = ({className}) => (
      <svg className={className ? `ui-icon ${className}` : "ui-icon"} aria-hidden="true" focusable="false">
        <use href={`#i-${id}`} />
      </svg>
    );
    icons.set(id, Icon);
  }
  return Icon;
}

// The dock draws a divider after the home item and before its footer. The product has five equal destinations
// and its screens are quiet (no decorative layers), so the slot renders nothing.
function NoDivider() {
  return null;
}

const subscribeHash = (onChange: () => void) => {
  window.addEventListener("hashchange", onChange);
  return () => window.removeEventListener("hashchange", onChange);
};
const readHash = () => window.location.hash;

function Menu({items, labels, version, logoutLabel, onLogout}: MenuOptions) {
  const hash = useSyncExternalStore(subscribeHash, readHash, readHash);
  // The router falls back to the first screen for an unknown hash and rewrites it without a hashchange event.
  const pathname = items.some(item => item.hash === hash) ? hash : items[0].hash;

  const [homeItem, ...navigation] = useMemo(
    () =>
      items.map(item => ({
        label: item.label,
        href: item.hash,
        icon: spriteIcon(item.icon),
        items: [],
      })),
    [items]
  );
  const Logout = spriteIcon("logout");

  // Logout lives in the footer of the rail. The shell also draws `utilities` above the bottom bar, where the
  // top bar already has the button, so that copy is hidden (host.css).
  const logout = (
    <button
      type="button"
      className={`${darkSidebarUtilityClassName} dozor-menu__logout`}
      aria-label={logoutLabel}
      title={logoutLabel}
      onClick={onLogout}
    >
      <Logout />
      <span className="dozor-menu__logout-label">{logoutLabel}</span>
    </button>
  );

  return (
    <SidebarShell
      mode="dozor"
      pathname={pathname}
      homeItem={homeItem}
      navigation={navigation}
      homeItemInNav
      brand={{
        title: labels.brandTitle,
        sigil: labels.brandSigil,
        ariaLabel: labels.brandAriaLabel,
        subtitle: version,
        href: homeItem.href,
      }}
      labels={labels}
      linkComponent={PlainLink}
      divider={NoDivider}
      utilities={logout}
      utilitiesPlacement="footer"
      watermark="none"
      exactMatchPaths={[]}
      // The route is the hash: keep the pinned state of the rail across navigation.
      remountOnPathChange={false}
      className="dozor-menu"
      mainClassName="dozor-menu__hidden"
      classNames={{
        ...darkSidebarShellClassNames,
        dock: {
          ...darkSidebarShellClassNames.dock,
          brandSubtitle: `${darkSidebarShellClassNames.dock?.brandSubtitle ?? ""} dozor-menu__version`,
        },
        mobileNav: {
          ...darkSidebarShellClassNames.mobileNav,
          utilities: `${darkSidebarShellClassNames.mobileNav?.utilities ?? ""} dozor-menu__hidden`,
        },
      }}
    >
      {null}
    </SidebarShell>
  );
}

function mount(el: HTMLElement, options: MenuOptions) {
  assertLabels(options.labels);
  const root = createRoot(el);
  let current = options;
  const render = () => root.render(<Menu {...current} />);
  render();
  return {
    /** Changes options after the mount, for example the version that arrives with the first status. */
    update(patch: Partial<MenuOptions>) {
      const next = {...current, ...patch};
      if (patch.labels) assertLabels(patch.labels);
      if ((Object.keys(next) as (keyof MenuOptions)[]).every(key => next[key] === current[key])) return;
      current = next;
      render();
    },
    unmount() {
      root.unmount();
    },
  };
}

(window as unknown as {DozorMenu: {mount: typeof mount}}).DozorMenu = {mount};
